### ISSUE TITLE
Move package wide support code to a dedicated module

### ISSUE THREAD

**Issue by berland** [equinor/fmu-ensemble#158]
There should be a module, say `common.py` that holds functions that are used by many other modules, instead of static and class functions spread around. There are many near circular imports happening while importing fmu.ensemble, and such a common module should help, if it does not depend on any of the existing packages to start.

**Comment by berland** [comment]
Candidates: 

realization: flatten and parse_number,  static_get_volumetric_rates (blocked by _glob_smry_keys), _cum_smrycol2rate, 
virtualrealization:  smry_cumulative

ensemble:shortcut2path, _convert_numeric_columns (remove this), _get_smry_dates

virtualensemble: _isvalidframe

**Comment by jondequinor** [comment]
I would recommend better naming than _common_. E.g. 

`util.realization.conversion` | `util.realization.arithmetic` | `util.ensemble.conversion` | …
------------ | ------------- | ------------- | -------------
`parse_number` | `static_get_volumetric_rates` | `_convert_numeric_columns`
`flatten` | `_cum_smrycol2rate` | `shortcut2path`

Simply because it's perhaps easier to _discover_ where something is when you're looking for it. "I need a util function for conversions for working with ensembles…"

**Comment by berland** [comment]
Thanks. Is this hierarchical structure possible to achieve without a deep directory structure and multiple `.py` files?

**Comment by jondequinor** [comment]
```
fmu-ensemble/
  util/
    __init__.py
    realization/
      __init__.py
      conversion/
        __init__.py
        numbers.py
```

This is completely normal, and very navigable using a modern editor. But this can grow in all directions, and still keep modules light and cohesive. I fear `common.py` quickly becomes 1000 LOC and disjointed (hummer&kanari).

**Comment by berland** [comment]
vim plugin ctrlp is now installed :)  

fmu-ensemble is at a somewhat stable state and large growth is perhaps not anticipated. I will think a little bit about how to categorize the current content of `utils.py` and might introduce one level.

**Comment by berland** [comment]
A possible categorization is `util/rates.py`, `util/dates.py` and `util/general.py`, where `general` is the hummer&kanari category.
