### ISSUE TITLE
Metadata regarding summary vector names

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/fmu-ensemble#87]
It would be useful to get metadata regarding summary vector names. E.g. see this issue https://github.com/equinor/webviz-subsurface/issues/208. Another use case is to automatically plot correct unit for a given vector along Y axis.

Relevant Python methods in `libecl`:
- [`unit`](https://github.com/equinor/libecl/blob/f1443476bc784f5b1d052e33cf1ea3235c41a00a/python/ecl/summary/ecl_smspec_node.py#L75)
- [`is_total`](https://github.com/equinor/libecl/blob/f1443476bc784f5b1d052e33cf1ea3235c41a00a/python/ecl/summary/ecl_smspec_node.py#L180)
- [`is_rate`](https://github.com/equinor/libecl/blob/f1443476bc784f5b1d052e33cf1ea3235c41a00a/python/ecl/summary/ecl_smspec_node.py#L170)
- [`is_historical`](https://github.com/equinor/libecl/blob/f1443476bc784f5b1d052e33cf1ea3235c41a00a/python/ecl/summary/ecl_smspec_node.py#L194)
- [`get_num`](https://github.com/equinor/libecl/blob/f1443476bc784f5b1d052e33cf1ea3235c41a00a/python/ecl/summary/ecl_smspec_node.py#L151)

**Comment by berland** [comment]
Any early comments on the PR @anders-kiaer ?

**Comment by berland** [comment]
@jokva, do you think this solution can survive a port to ecl3?

**Comment by anders-kiaer** [comment]
> Any early comments on the PR @anders-kiaer ?
Looks good to me at first glance 👏👍  I think, as you also have started doing, to let metadata be a separate minimal data structure is a good thing, instead of extending the already big summary dataframe with redundant data (constant values per vector for all timesteps).

**Comment by jokva** [comment]
I suppose the fmu-ensemble side of it can live just fine, but if is_rate and similar survives[1], it will probably not be members on a summary object. That's the easier port, though.

[1] It might, it's useful information to centralise, at least advisory.

**Comment by berland** [comment]
Thanks both. 

Outstanding for the issue is then
 * [ ] Add to RealizationCombination. Determine how to deal with a potential situation when metadata differs in a linear combination of realizations for a specific column (if it can happen).
 * [ ] Determine if every realization should be asked for its metadata in an ensemble, or if shortcuts should be made. Add to ScratchEnsemble, EnsembleCombination.
 * [ ] Determine how to represent in a VirtualEnsemble/VirtualRealization. Perhaps as a dataframe that can be dumped to csv. Which filename to use for localpath and when dumped to disk.

**Comment by berland** [comment]
RealizationCombination/EnsembleCombination will be skipped unless the need is there.

**Comment by berland** [comment]
*Combination turned out to be easy. Added.

**Comment by anders-kiaer** [comment]
Solved in #89.
